/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PrivateAccountV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PrivateAccountV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        vcoinName?: string;
        coinId?: string;
        balanceAmount?: string;
        balanceAmountChange?: string;
        frozenAmount?: string;
        frozenAmountChange?: string;
        type?: string;
        time?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("vcoinName" in data && data.vcoinName != undefined) {
                this.vcoinName = data.vcoinName;
            }
            if ("coinId" in data && data.coinId != undefined) {
                this.coinId = data.coinId;
            }
            if ("balanceAmount" in data && data.balanceAmount != undefined) {
                this.balanceAmount = data.balanceAmount;
            }
            if ("balanceAmountChange" in data && data.balanceAmountChange != undefined) {
                this.balanceAmountChange = data.balanceAmountChange;
            }
            if ("frozenAmount" in data && data.frozenAmount != undefined) {
                this.frozenAmount = data.frozenAmount;
            }
            if ("frozenAmountChange" in data && data.frozenAmountChange != undefined) {
                this.frozenAmountChange = data.frozenAmountChange;
            }
            if ("type" in data && data.type != undefined) {
                this.type = data.type;
            }
            if ("time" in data && data.time != undefined) {
                this.time = data.time;
            }
        }
    }
    get vcoinName() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set vcoinName(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get coinId() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set coinId(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get balanceAmount() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set balanceAmount(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get balanceAmountChange() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set balanceAmountChange(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get frozenAmount() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set frozenAmount(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get frozenAmountChange() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set frozenAmountChange(value: string) {
        pb_1.Message.setField(this, 6, value);
    }
    get type() {
        return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
    }
    set type(value: string) {
        pb_1.Message.setField(this, 7, value);
    }
    get time() {
        return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
    }
    set time(value: number) {
        pb_1.Message.setField(this, 8, value);
    }
    static fromObject(data: {
        vcoinName?: string;
        coinId?: string;
        balanceAmount?: string;
        balanceAmountChange?: string;
        frozenAmount?: string;
        frozenAmountChange?: string;
        type?: string;
        time?: number;
    }): PrivateAccountV3Api {
        const message = new PrivateAccountV3Api({});
        if (data.vcoinName != null) {
            message.vcoinName = data.vcoinName;
        }
        if (data.coinId != null) {
            message.coinId = data.coinId;
        }
        if (data.balanceAmount != null) {
            message.balanceAmount = data.balanceAmount;
        }
        if (data.balanceAmountChange != null) {
            message.balanceAmountChange = data.balanceAmountChange;
        }
        if (data.frozenAmount != null) {
            message.frozenAmount = data.frozenAmount;
        }
        if (data.frozenAmountChange != null) {
            message.frozenAmountChange = data.frozenAmountChange;
        }
        if (data.type != null) {
            message.type = data.type;
        }
        if (data.time != null) {
            message.time = data.time;
        }
        return message;
    }
    toObject() {
        const data: {
            vcoinName?: string;
            coinId?: string;
            balanceAmount?: string;
            balanceAmountChange?: string;
            frozenAmount?: string;
            frozenAmountChange?: string;
            type?: string;
            time?: number;
        } = {};
        if (this.vcoinName != null) {
            data.vcoinName = this.vcoinName;
        }
        if (this.coinId != null) {
            data.coinId = this.coinId;
        }
        if (this.balanceAmount != null) {
            data.balanceAmount = this.balanceAmount;
        }
        if (this.balanceAmountChange != null) {
            data.balanceAmountChange = this.balanceAmountChange;
        }
        if (this.frozenAmount != null) {
            data.frozenAmount = this.frozenAmount;
        }
        if (this.frozenAmountChange != null) {
            data.frozenAmountChange = this.frozenAmountChange;
        }
        if (this.type != null) {
            data.type = this.type;
        }
        if (this.time != null) {
            data.time = this.time;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.vcoinName.length)
            writer.writeString(1, this.vcoinName);
        if (this.coinId.length)
            writer.writeString(2, this.coinId);
        if (this.balanceAmount.length)
            writer.writeString(3, this.balanceAmount);
        if (this.balanceAmountChange.length)
            writer.writeString(4, this.balanceAmountChange);
        if (this.frozenAmount.length)
            writer.writeString(5, this.frozenAmount);
        if (this.frozenAmountChange.length)
            writer.writeString(6, this.frozenAmountChange);
        if (this.type.length)
            writer.writeString(7, this.type);
        if (this.time != 0)
            writer.writeInt64(8, this.time);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PrivateAccountV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PrivateAccountV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.vcoinName = reader.readString();
                    break;
                case 2:
                    message.coinId = reader.readString();
                    break;
                case 3:
                    message.balanceAmount = reader.readString();
                    break;
                case 4:
                    message.balanceAmountChange = reader.readString();
                    break;
                case 5:
                    message.frozenAmount = reader.readString();
                    break;
                case 6:
                    message.frozenAmountChange = reader.readString();
                    break;
                case 7:
                    message.type = reader.readString();
                    break;
                case 8:
                    message.time = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PrivateAccountV3Api {
        return PrivateAccountV3Api.deserialize(bytes);
    }
}
