/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PrivateDealsV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PrivateDealsV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        price?: string;
        quantity?: string;
        amount?: string;
        tradeType?: number;
        isMaker?: boolean;
        isSelfTrade?: boolean;
        tradeId?: string;
        clientOrderId?: string;
        orderId?: string;
        feeAmount?: string;
        feeCurrency?: string;
        time?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("price" in data && data.price != undefined) {
                this.price = data.price;
            }
            if ("quantity" in data && data.quantity != undefined) {
                this.quantity = data.quantity;
            }
            if ("amount" in data && data.amount != undefined) {
                this.amount = data.amount;
            }
            if ("tradeType" in data && data.tradeType != undefined) {
                this.tradeType = data.tradeType;
            }
            if ("isMaker" in data && data.isMaker != undefined) {
                this.isMaker = data.isMaker;
            }
            if ("isSelfTrade" in data && data.isSelfTrade != undefined) {
                this.isSelfTrade = data.isSelfTrade;
            }
            if ("tradeId" in data && data.tradeId != undefined) {
                this.tradeId = data.tradeId;
            }
            if ("clientOrderId" in data && data.clientOrderId != undefined) {
                this.clientOrderId = data.clientOrderId;
            }
            if ("orderId" in data && data.orderId != undefined) {
                this.orderId = data.orderId;
            }
            if ("feeAmount" in data && data.feeAmount != undefined) {
                this.feeAmount = data.feeAmount;
            }
            if ("feeCurrency" in data && data.feeCurrency != undefined) {
                this.feeCurrency = data.feeCurrency;
            }
            if ("time" in data && data.time != undefined) {
                this.time = data.time;
            }
        }
    }
    get price() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set price(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get quantity() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set quantity(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get amount() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set amount(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get tradeType() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set tradeType(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    get isMaker() {
        return pb_1.Message.getFieldWithDefault(this, 5, false) as boolean;
    }
    set isMaker(value: boolean) {
        pb_1.Message.setField(this, 5, value);
    }
    get isSelfTrade() {
        return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
    }
    set isSelfTrade(value: boolean) {
        pb_1.Message.setField(this, 6, value);
    }
    get tradeId() {
        return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
    }
    set tradeId(value: string) {
        pb_1.Message.setField(this, 7, value);
    }
    get clientOrderId() {
        return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
    }
    set clientOrderId(value: string) {
        pb_1.Message.setField(this, 8, value);
    }
    get orderId() {
        return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
    }
    set orderId(value: string) {
        pb_1.Message.setField(this, 9, value);
    }
    get feeAmount() {
        return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
    }
    set feeAmount(value: string) {
        pb_1.Message.setField(this, 10, value);
    }
    get feeCurrency() {
        return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
    }
    set feeCurrency(value: string) {
        pb_1.Message.setField(this, 11, value);
    }
    get time() {
        return pb_1.Message.getFieldWithDefault(this, 12, 0) as number;
    }
    set time(value: number) {
        pb_1.Message.setField(this, 12, value);
    }
    static fromObject(data: {
        price?: string;
        quantity?: string;
        amount?: string;
        tradeType?: number;
        isMaker?: boolean;
        isSelfTrade?: boolean;
        tradeId?: string;
        clientOrderId?: string;
        orderId?: string;
        feeAmount?: string;
        feeCurrency?: string;
        time?: number;
    }): PrivateDealsV3Api {
        const message = new PrivateDealsV3Api({});
        if (data.price != null) {
            message.price = data.price;
        }
        if (data.quantity != null) {
            message.quantity = data.quantity;
        }
        if (data.amount != null) {
            message.amount = data.amount;
        }
        if (data.tradeType != null) {
            message.tradeType = data.tradeType;
        }
        if (data.isMaker != null) {
            message.isMaker = data.isMaker;
        }
        if (data.isSelfTrade != null) {
            message.isSelfTrade = data.isSelfTrade;
        }
        if (data.tradeId != null) {
            message.tradeId = data.tradeId;
        }
        if (data.clientOrderId != null) {
            message.clientOrderId = data.clientOrderId;
        }
        if (data.orderId != null) {
            message.orderId = data.orderId;
        }
        if (data.feeAmount != null) {
            message.feeAmount = data.feeAmount;
        }
        if (data.feeCurrency != null) {
            message.feeCurrency = data.feeCurrency;
        }
        if (data.time != null) {
            message.time = data.time;
        }
        return message;
    }
    toObject() {
        const data: {
            price?: string;
            quantity?: string;
            amount?: string;
            tradeType?: number;
            isMaker?: boolean;
            isSelfTrade?: boolean;
            tradeId?: string;
            clientOrderId?: string;
            orderId?: string;
            feeAmount?: string;
            feeCurrency?: string;
            time?: number;
        } = {};
        if (this.price != null) {
            data.price = this.price;
        }
        if (this.quantity != null) {
            data.quantity = this.quantity;
        }
        if (this.amount != null) {
            data.amount = this.amount;
        }
        if (this.tradeType != null) {
            data.tradeType = this.tradeType;
        }
        if (this.isMaker != null) {
            data.isMaker = this.isMaker;
        }
        if (this.isSelfTrade != null) {
            data.isSelfTrade = this.isSelfTrade;
        }
        if (this.tradeId != null) {
            data.tradeId = this.tradeId;
        }
        if (this.clientOrderId != null) {
            data.clientOrderId = this.clientOrderId;
        }
        if (this.orderId != null) {
            data.orderId = this.orderId;
        }
        if (this.feeAmount != null) {
            data.feeAmount = this.feeAmount;
        }
        if (this.feeCurrency != null) {
            data.feeCurrency = this.feeCurrency;
        }
        if (this.time != null) {
            data.time = this.time;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.price.length)
            writer.writeString(1, this.price);
        if (this.quantity.length)
            writer.writeString(2, this.quantity);
        if (this.amount.length)
            writer.writeString(3, this.amount);
        if (this.tradeType != 0)
            writer.writeInt32(4, this.tradeType);
        if (this.isMaker != false)
            writer.writeBool(5, this.isMaker);
        if (this.isSelfTrade != false)
            writer.writeBool(6, this.isSelfTrade);
        if (this.tradeId.length)
            writer.writeString(7, this.tradeId);
        if (this.clientOrderId.length)
            writer.writeString(8, this.clientOrderId);
        if (this.orderId.length)
            writer.writeString(9, this.orderId);
        if (this.feeAmount.length)
            writer.writeString(10, this.feeAmount);
        if (this.feeCurrency.length)
            writer.writeString(11, this.feeCurrency);
        if (this.time != 0)
            writer.writeInt64(12, this.time);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PrivateDealsV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PrivateDealsV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.price = reader.readString();
                    break;
                case 2:
                    message.quantity = reader.readString();
                    break;
                case 3:
                    message.amount = reader.readString();
                    break;
                case 4:
                    message.tradeType = reader.readInt32();
                    break;
                case 5:
                    message.isMaker = reader.readBool();
                    break;
                case 6:
                    message.isSelfTrade = reader.readBool();
                    break;
                case 7:
                    message.tradeId = reader.readString();
                    break;
                case 8:
                    message.clientOrderId = reader.readString();
                    break;
                case 9:
                    message.orderId = reader.readString();
                    break;
                case 10:
                    message.feeAmount = reader.readString();
                    break;
                case 11:
                    message.feeCurrency = reader.readString();
                    break;
                case 12:
                    message.time = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PrivateDealsV3Api {
        return PrivateDealsV3Api.deserialize(bytes);
    }
}
