/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PrivateOrdersV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PrivateOrdersV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [[12], [17], [18], [19], [20], [21], [22], [23], [24], [25], [26]];
    constructor(data?: any[] | ({
        id?: string;
        clientId?: string;
        price?: string;
        quantity?: string;
        amount?: string;
        avgPrice?: string;
        orderType?: number;
        tradeType?: number;
        isMaker?: boolean;
        remainAmount?: string;
        remainQuantity?: string;
        cumulativeQuantity?: string;
        cumulativeAmount?: string;
        status?: number;
        createTime?: number;
    } & (({
        lastDealQuantity?: string;
    }) | ({
        market?: string;
    }) | ({
        triggerType?: number;
    }) | ({
        triggerPrice?: string;
    }) | ({
        state?: number;
    }) | ({
        ocoId?: string;
    }) | ({
        routeFactor?: string;
    }) | ({
        symbolId?: string;
    }) | ({
        marketId?: string;
    }) | ({
        marketCurrencyId?: string;
    }) | ({
        currencyId?: string;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("clientId" in data && data.clientId != undefined) {
                this.clientId = data.clientId;
            }
            if ("price" in data && data.price != undefined) {
                this.price = data.price;
            }
            if ("quantity" in data && data.quantity != undefined) {
                this.quantity = data.quantity;
            }
            if ("amount" in data && data.amount != undefined) {
                this.amount = data.amount;
            }
            if ("avgPrice" in data && data.avgPrice != undefined) {
                this.avgPrice = data.avgPrice;
            }
            if ("orderType" in data && data.orderType != undefined) {
                this.orderType = data.orderType;
            }
            if ("tradeType" in data && data.tradeType != undefined) {
                this.tradeType = data.tradeType;
            }
            if ("isMaker" in data && data.isMaker != undefined) {
                this.isMaker = data.isMaker;
            }
            if ("remainAmount" in data && data.remainAmount != undefined) {
                this.remainAmount = data.remainAmount;
            }
            if ("remainQuantity" in data && data.remainQuantity != undefined) {
                this.remainQuantity = data.remainQuantity;
            }
            if ("lastDealQuantity" in data && data.lastDealQuantity != undefined) {
                this.lastDealQuantity = data.lastDealQuantity;
            }
            if ("cumulativeQuantity" in data && data.cumulativeQuantity != undefined) {
                this.cumulativeQuantity = data.cumulativeQuantity;
            }
            if ("cumulativeAmount" in data && data.cumulativeAmount != undefined) {
                this.cumulativeAmount = data.cumulativeAmount;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("createTime" in data && data.createTime != undefined) {
                this.createTime = data.createTime;
            }
            if ("market" in data && data.market != undefined) {
                this.market = data.market;
            }
            if ("triggerType" in data && data.triggerType != undefined) {
                this.triggerType = data.triggerType;
            }
            if ("triggerPrice" in data && data.triggerPrice != undefined) {
                this.triggerPrice = data.triggerPrice;
            }
            if ("state" in data && data.state != undefined) {
                this.state = data.state;
            }
            if ("ocoId" in data && data.ocoId != undefined) {
                this.ocoId = data.ocoId;
            }
            if ("routeFactor" in data && data.routeFactor != undefined) {
                this.routeFactor = data.routeFactor;
            }
            if ("symbolId" in data && data.symbolId != undefined) {
                this.symbolId = data.symbolId;
            }
            if ("marketId" in data && data.marketId != undefined) {
                this.marketId = data.marketId;
            }
            if ("marketCurrencyId" in data && data.marketCurrencyId != undefined) {
                this.marketCurrencyId = data.marketCurrencyId;
            }
            if ("currencyId" in data && data.currencyId != undefined) {
                this.currencyId = data.currencyId;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get clientId() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set clientId(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get price() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set price(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get quantity() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set quantity(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get amount() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set amount(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get avgPrice() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set avgPrice(value: string) {
        pb_1.Message.setField(this, 6, value);
    }
    get orderType() {
        return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
    }
    set orderType(value: number) {
        pb_1.Message.setField(this, 7, value);
    }
    get tradeType() {
        return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
    }
    set tradeType(value: number) {
        pb_1.Message.setField(this, 8, value);
    }
    get isMaker() {
        return pb_1.Message.getFieldWithDefault(this, 9, false) as boolean;
    }
    set isMaker(value: boolean) {
        pb_1.Message.setField(this, 9, value);
    }
    get remainAmount() {
        return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
    }
    set remainAmount(value: string) {
        pb_1.Message.setField(this, 10, value);
    }
    get remainQuantity() {
        return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
    }
    set remainQuantity(value: string) {
        pb_1.Message.setField(this, 11, value);
    }
    get lastDealQuantity() {
        return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
    }
    set lastDealQuantity(value: string) {
        pb_1.Message.setOneofField(this, 12, this.#one_of_decls[0], value);
    }
    get has_lastDealQuantity() {
        return pb_1.Message.getField(this, 12) != null;
    }
    get cumulativeQuantity() {
        return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
    }
    set cumulativeQuantity(value: string) {
        pb_1.Message.setField(this, 13, value);
    }
    get cumulativeAmount() {
        return pb_1.Message.getFieldWithDefault(this, 14, "") as string;
    }
    set cumulativeAmount(value: string) {
        pb_1.Message.setField(this, 14, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 15, 0) as number;
    }
    set status(value: number) {
        pb_1.Message.setField(this, 15, value);
    }
    get createTime() {
        return pb_1.Message.getFieldWithDefault(this, 16, 0) as number;
    }
    set createTime(value: number) {
        pb_1.Message.setField(this, 16, value);
    }
    get market() {
        return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
    }
    set market(value: string) {
        pb_1.Message.setOneofField(this, 17, this.#one_of_decls[1], value);
    }
    get has_market() {
        return pb_1.Message.getField(this, 17) != null;
    }
    get triggerType() {
        return pb_1.Message.getFieldWithDefault(this, 18, 0) as number;
    }
    set triggerType(value: number) {
        pb_1.Message.setOneofField(this, 18, this.#one_of_decls[2], value);
    }
    get has_triggerType() {
        return pb_1.Message.getField(this, 18) != null;
    }
    get triggerPrice() {
        return pb_1.Message.getFieldWithDefault(this, 19, "") as string;
    }
    set triggerPrice(value: string) {
        pb_1.Message.setOneofField(this, 19, this.#one_of_decls[3], value);
    }
    get has_triggerPrice() {
        return pb_1.Message.getField(this, 19) != null;
    }
    get state() {
        return pb_1.Message.getFieldWithDefault(this, 20, 0) as number;
    }
    set state(value: number) {
        pb_1.Message.setOneofField(this, 20, this.#one_of_decls[4], value);
    }
    get has_state() {
        return pb_1.Message.getField(this, 20) != null;
    }
    get ocoId() {
        return pb_1.Message.getFieldWithDefault(this, 21, "") as string;
    }
    set ocoId(value: string) {
        pb_1.Message.setOneofField(this, 21, this.#one_of_decls[5], value);
    }
    get has_ocoId() {
        return pb_1.Message.getField(this, 21) != null;
    }
    get routeFactor() {
        return pb_1.Message.getFieldWithDefault(this, 22, "") as string;
    }
    set routeFactor(value: string) {
        pb_1.Message.setOneofField(this, 22, this.#one_of_decls[6], value);
    }
    get has_routeFactor() {
        return pb_1.Message.getField(this, 22) != null;
    }
    get symbolId() {
        return pb_1.Message.getFieldWithDefault(this, 23, "") as string;
    }
    set symbolId(value: string) {
        pb_1.Message.setOneofField(this, 23, this.#one_of_decls[7], value);
    }
    get has_symbolId() {
        return pb_1.Message.getField(this, 23) != null;
    }
    get marketId() {
        return pb_1.Message.getFieldWithDefault(this, 24, "") as string;
    }
    set marketId(value: string) {
        pb_1.Message.setOneofField(this, 24, this.#one_of_decls[8], value);
    }
    get has_marketId() {
        return pb_1.Message.getField(this, 24) != null;
    }
    get marketCurrencyId() {
        return pb_1.Message.getFieldWithDefault(this, 25, "") as string;
    }
    set marketCurrencyId(value: string) {
        pb_1.Message.setOneofField(this, 25, this.#one_of_decls[9], value);
    }
    get has_marketCurrencyId() {
        return pb_1.Message.getField(this, 25) != null;
    }
    get currencyId() {
        return pb_1.Message.getFieldWithDefault(this, 26, "") as string;
    }
    set currencyId(value: string) {
        pb_1.Message.setOneofField(this, 26, this.#one_of_decls[10], value);
    }
    get has_currencyId() {
        return pb_1.Message.getField(this, 26) != null;
    }
    get _lastDealQuantity() {
        const cases: {
            [index: number]: "none" | "lastDealQuantity";
        } = {
            0: "none",
            12: "lastDealQuantity"
        };
        return cases[pb_1.Message.computeOneofCase(this, [12])];
    }
    get _market() {
        const cases: {
            [index: number]: "none" | "market";
        } = {
            0: "none",
            17: "market"
        };
        return cases[pb_1.Message.computeOneofCase(this, [17])];
    }
    get _triggerType() {
        const cases: {
            [index: number]: "none" | "triggerType";
        } = {
            0: "none",
            18: "triggerType"
        };
        return cases[pb_1.Message.computeOneofCase(this, [18])];
    }
    get _triggerPrice() {
        const cases: {
            [index: number]: "none" | "triggerPrice";
        } = {
            0: "none",
            19: "triggerPrice"
        };
        return cases[pb_1.Message.computeOneofCase(this, [19])];
    }
    get _state() {
        const cases: {
            [index: number]: "none" | "state";
        } = {
            0: "none",
            20: "state"
        };
        return cases[pb_1.Message.computeOneofCase(this, [20])];
    }
    get _ocoId() {
        const cases: {
            [index: number]: "none" | "ocoId";
        } = {
            0: "none",
            21: "ocoId"
        };
        return cases[pb_1.Message.computeOneofCase(this, [21])];
    }
    get _routeFactor() {
        const cases: {
            [index: number]: "none" | "routeFactor";
        } = {
            0: "none",
            22: "routeFactor"
        };
        return cases[pb_1.Message.computeOneofCase(this, [22])];
    }
    get _symbolId() {
        const cases: {
            [index: number]: "none" | "symbolId";
        } = {
            0: "none",
            23: "symbolId"
        };
        return cases[pb_1.Message.computeOneofCase(this, [23])];
    }
    get _marketId() {
        const cases: {
            [index: number]: "none" | "marketId";
        } = {
            0: "none",
            24: "marketId"
        };
        return cases[pb_1.Message.computeOneofCase(this, [24])];
    }
    get _marketCurrencyId() {
        const cases: {
            [index: number]: "none" | "marketCurrencyId";
        } = {
            0: "none",
            25: "marketCurrencyId"
        };
        return cases[pb_1.Message.computeOneofCase(this, [25])];
    }
    get _currencyId() {
        const cases: {
            [index: number]: "none" | "currencyId";
        } = {
            0: "none",
            26: "currencyId"
        };
        return cases[pb_1.Message.computeOneofCase(this, [26])];
    }
    static fromObject(data: {
        id?: string;
        clientId?: string;
        price?: string;
        quantity?: string;
        amount?: string;
        avgPrice?: string;
        orderType?: number;
        tradeType?: number;
        isMaker?: boolean;
        remainAmount?: string;
        remainQuantity?: string;
        lastDealQuantity?: string;
        cumulativeQuantity?: string;
        cumulativeAmount?: string;
        status?: number;
        createTime?: number;
        market?: string;
        triggerType?: number;
        triggerPrice?: string;
        state?: number;
        ocoId?: string;
        routeFactor?: string;
        symbolId?: string;
        marketId?: string;
        marketCurrencyId?: string;
        currencyId?: string;
    }): PrivateOrdersV3Api {
        const message = new PrivateOrdersV3Api({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.clientId != null) {
            message.clientId = data.clientId;
        }
        if (data.price != null) {
            message.price = data.price;
        }
        if (data.quantity != null) {
            message.quantity = data.quantity;
        }
        if (data.amount != null) {
            message.amount = data.amount;
        }
        if (data.avgPrice != null) {
            message.avgPrice = data.avgPrice;
        }
        if (data.orderType != null) {
            message.orderType = data.orderType;
        }
        if (data.tradeType != null) {
            message.tradeType = data.tradeType;
        }
        if (data.isMaker != null) {
            message.isMaker = data.isMaker;
        }
        if (data.remainAmount != null) {
            message.remainAmount = data.remainAmount;
        }
        if (data.remainQuantity != null) {
            message.remainQuantity = data.remainQuantity;
        }
        if (data.lastDealQuantity != null) {
            message.lastDealQuantity = data.lastDealQuantity;
        }
        if (data.cumulativeQuantity != null) {
            message.cumulativeQuantity = data.cumulativeQuantity;
        }
        if (data.cumulativeAmount != null) {
            message.cumulativeAmount = data.cumulativeAmount;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.createTime != null) {
            message.createTime = data.createTime;
        }
        if (data.market != null) {
            message.market = data.market;
        }
        if (data.triggerType != null) {
            message.triggerType = data.triggerType;
        }
        if (data.triggerPrice != null) {
            message.triggerPrice = data.triggerPrice;
        }
        if (data.state != null) {
            message.state = data.state;
        }
        if (data.ocoId != null) {
            message.ocoId = data.ocoId;
        }
        if (data.routeFactor != null) {
            message.routeFactor = data.routeFactor;
        }
        if (data.symbolId != null) {
            message.symbolId = data.symbolId;
        }
        if (data.marketId != null) {
            message.marketId = data.marketId;
        }
        if (data.marketCurrencyId != null) {
            message.marketCurrencyId = data.marketCurrencyId;
        }
        if (data.currencyId != null) {
            message.currencyId = data.currencyId;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            clientId?: string;
            price?: string;
            quantity?: string;
            amount?: string;
            avgPrice?: string;
            orderType?: number;
            tradeType?: number;
            isMaker?: boolean;
            remainAmount?: string;
            remainQuantity?: string;
            lastDealQuantity?: string;
            cumulativeQuantity?: string;
            cumulativeAmount?: string;
            status?: number;
            createTime?: number;
            market?: string;
            triggerType?: number;
            triggerPrice?: string;
            state?: number;
            ocoId?: string;
            routeFactor?: string;
            symbolId?: string;
            marketId?: string;
            marketCurrencyId?: string;
            currencyId?: string;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.clientId != null) {
            data.clientId = this.clientId;
        }
        if (this.price != null) {
            data.price = this.price;
        }
        if (this.quantity != null) {
            data.quantity = this.quantity;
        }
        if (this.amount != null) {
            data.amount = this.amount;
        }
        if (this.avgPrice != null) {
            data.avgPrice = this.avgPrice;
        }
        if (this.orderType != null) {
            data.orderType = this.orderType;
        }
        if (this.tradeType != null) {
            data.tradeType = this.tradeType;
        }
        if (this.isMaker != null) {
            data.isMaker = this.isMaker;
        }
        if (this.remainAmount != null) {
            data.remainAmount = this.remainAmount;
        }
        if (this.remainQuantity != null) {
            data.remainQuantity = this.remainQuantity;
        }
        if (this.lastDealQuantity != null) {
            data.lastDealQuantity = this.lastDealQuantity;
        }
        if (this.cumulativeQuantity != null) {
            data.cumulativeQuantity = this.cumulativeQuantity;
        }
        if (this.cumulativeAmount != null) {
            data.cumulativeAmount = this.cumulativeAmount;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.createTime != null) {
            data.createTime = this.createTime;
        }
        if (this.market != null) {
            data.market = this.market;
        }
        if (this.triggerType != null) {
            data.triggerType = this.triggerType;
        }
        if (this.triggerPrice != null) {
            data.triggerPrice = this.triggerPrice;
        }
        if (this.state != null) {
            data.state = this.state;
        }
        if (this.ocoId != null) {
            data.ocoId = this.ocoId;
        }
        if (this.routeFactor != null) {
            data.routeFactor = this.routeFactor;
        }
        if (this.symbolId != null) {
            data.symbolId = this.symbolId;
        }
        if (this.marketId != null) {
            data.marketId = this.marketId;
        }
        if (this.marketCurrencyId != null) {
            data.marketCurrencyId = this.marketCurrencyId;
        }
        if (this.currencyId != null) {
            data.currencyId = this.currencyId;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.clientId.length)
            writer.writeString(2, this.clientId);
        if (this.price.length)
            writer.writeString(3, this.price);
        if (this.quantity.length)
            writer.writeString(4, this.quantity);
        if (this.amount.length)
            writer.writeString(5, this.amount);
        if (this.avgPrice.length)
            writer.writeString(6, this.avgPrice);
        if (this.orderType != 0)
            writer.writeInt32(7, this.orderType);
        if (this.tradeType != 0)
            writer.writeInt32(8, this.tradeType);
        if (this.isMaker != false)
            writer.writeBool(9, this.isMaker);
        if (this.remainAmount.length)
            writer.writeString(10, this.remainAmount);
        if (this.remainQuantity.length)
            writer.writeString(11, this.remainQuantity);
        if (this.has_lastDealQuantity)
            writer.writeString(12, this.lastDealQuantity);
        if (this.cumulativeQuantity.length)
            writer.writeString(13, this.cumulativeQuantity);
        if (this.cumulativeAmount.length)
            writer.writeString(14, this.cumulativeAmount);
        if (this.status != 0)
            writer.writeInt32(15, this.status);
        if (this.createTime != 0)
            writer.writeInt64(16, this.createTime);
        if (this.has_market)
            writer.writeString(17, this.market);
        if (this.has_triggerType)
            writer.writeInt32(18, this.triggerType);
        if (this.has_triggerPrice)
            writer.writeString(19, this.triggerPrice);
        if (this.has_state)
            writer.writeInt32(20, this.state);
        if (this.has_ocoId)
            writer.writeString(21, this.ocoId);
        if (this.has_routeFactor)
            writer.writeString(22, this.routeFactor);
        if (this.has_symbolId)
            writer.writeString(23, this.symbolId);
        if (this.has_marketId)
            writer.writeString(24, this.marketId);
        if (this.has_marketCurrencyId)
            writer.writeString(25, this.marketCurrencyId);
        if (this.has_currencyId)
            writer.writeString(26, this.currencyId);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PrivateOrdersV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PrivateOrdersV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.clientId = reader.readString();
                    break;
                case 3:
                    message.price = reader.readString();
                    break;
                case 4:
                    message.quantity = reader.readString();
                    break;
                case 5:
                    message.amount = reader.readString();
                    break;
                case 6:
                    message.avgPrice = reader.readString();
                    break;
                case 7:
                    message.orderType = reader.readInt32();
                    break;
                case 8:
                    message.tradeType = reader.readInt32();
                    break;
                case 9:
                    message.isMaker = reader.readBool();
                    break;
                case 10:
                    message.remainAmount = reader.readString();
                    break;
                case 11:
                    message.remainQuantity = reader.readString();
                    break;
                case 12:
                    message.lastDealQuantity = reader.readString();
                    break;
                case 13:
                    message.cumulativeQuantity = reader.readString();
                    break;
                case 14:
                    message.cumulativeAmount = reader.readString();
                    break;
                case 15:
                    message.status = reader.readInt32();
                    break;
                case 16:
                    message.createTime = reader.readInt64();
                    break;
                case 17:
                    message.market = reader.readString();
                    break;
                case 18:
                    message.triggerType = reader.readInt32();
                    break;
                case 19:
                    message.triggerPrice = reader.readString();
                    break;
                case 20:
                    message.state = reader.readInt32();
                    break;
                case 21:
                    message.ocoId = reader.readString();
                    break;
                case 22:
                    message.routeFactor = reader.readString();
                    break;
                case 23:
                    message.symbolId = reader.readString();
                    break;
                case 24:
                    message.marketId = reader.readString();
                    break;
                case 25:
                    message.marketCurrencyId = reader.readString();
                    break;
                case 26:
                    message.currencyId = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PrivateOrdersV3Api {
        return PrivateOrdersV3Api.deserialize(bytes);
    }
}
