/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PublicBookTickerBatchV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./PublicBookTickerV3Api.ts";
import * as pb_1 from "google-protobuf";
export class PublicBookTickerBatchV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        items?: dependency_1.PublicBookTickerV3Api[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("items" in data && data.items != undefined) {
                this.items = data.items;
            }
        }
    }
    get items() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.PublicBookTickerV3Api, 1) as dependency_1.PublicBookTickerV3Api[];
    }
    set items(value: dependency_1.PublicBookTickerV3Api[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        items?: ReturnType<typeof dependency_1.PublicBookTickerV3Api.prototype.toObject>[];
    }): PublicBookTickerBatchV3Api {
        const message = new PublicBookTickerBatchV3Api({});
        if (data.items != null) {
            message.items = data.items.map(item => dependency_1.PublicBookTickerV3Api.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            items?: ReturnType<typeof dependency_1.PublicBookTickerV3Api.prototype.toObject>[];
        } = {};
        if (this.items != null) {
            data.items = this.items.map((item: dependency_1.PublicBookTickerV3Api) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.items.length)
            writer.writeRepeatedMessage(1, this.items, (item: dependency_1.PublicBookTickerV3Api) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicBookTickerBatchV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicBookTickerBatchV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.items, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_1.PublicBookTickerV3Api.deserialize(reader), dependency_1.PublicBookTickerV3Api));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicBookTickerBatchV3Api {
        return PublicBookTickerBatchV3Api.deserialize(bytes);
    }
}
