/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PublicAggreDealsV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PublicAggreDealsV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        deals?: PublicAggreDealsV3ApiItem[];
        eventType?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("deals" in data && data.deals != undefined) {
                this.deals = data.deals;
            }
            if ("eventType" in data && data.eventType != undefined) {
                this.eventType = data.eventType;
            }
        }
    }
    get deals() {
        return pb_1.Message.getRepeatedWrapperField(this, PublicAggreDealsV3ApiItem, 1) as PublicAggreDealsV3ApiItem[];
    }
    set deals(value: PublicAggreDealsV3ApiItem[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    get eventType() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set eventType(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        deals?: ReturnType<typeof PublicAggreDealsV3ApiItem.prototype.toObject>[];
        eventType?: string;
    }): PublicAggreDealsV3Api {
        const message = new PublicAggreDealsV3Api({});
        if (data.deals != null) {
            message.deals = data.deals.map(item => PublicAggreDealsV3ApiItem.fromObject(item));
        }
        if (data.eventType != null) {
            message.eventType = data.eventType;
        }
        return message;
    }
    toObject() {
        const data: {
            deals?: ReturnType<typeof PublicAggreDealsV3ApiItem.prototype.toObject>[];
            eventType?: string;
        } = {};
        if (this.deals != null) {
            data.deals = this.deals.map((item: PublicAggreDealsV3ApiItem) => item.toObject());
        }
        if (this.eventType != null) {
            data.eventType = this.eventType;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.deals.length)
            writer.writeRepeatedMessage(1, this.deals, (item: PublicAggreDealsV3ApiItem) => item.serialize(writer));
        if (this.eventType.length)
            writer.writeString(2, this.eventType);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicAggreDealsV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicAggreDealsV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.deals, () => pb_1.Message.addToRepeatedWrapperField(message, 1, PublicAggreDealsV3ApiItem.deserialize(reader), PublicAggreDealsV3ApiItem));
                    break;
                case 2:
                    message.eventType = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicAggreDealsV3Api {
        return PublicAggreDealsV3Api.deserialize(bytes);
    }
}
export class PublicAggreDealsV3ApiItem extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        price?: string;
        quantity?: string;
        tradeType?: number;
        time?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("price" in data && data.price != undefined) {
                this.price = data.price;
            }
            if ("quantity" in data && data.quantity != undefined) {
                this.quantity = data.quantity;
            }
            if ("tradeType" in data && data.tradeType != undefined) {
                this.tradeType = data.tradeType;
            }
            if ("time" in data && data.time != undefined) {
                this.time = data.time;
            }
        }
    }
    get price() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set price(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get quantity() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set quantity(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get tradeType() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set tradeType(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get time() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set time(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        price?: string;
        quantity?: string;
        tradeType?: number;
        time?: number;
    }): PublicAggreDealsV3ApiItem {
        const message = new PublicAggreDealsV3ApiItem({});
        if (data.price != null) {
            message.price = data.price;
        }
        if (data.quantity != null) {
            message.quantity = data.quantity;
        }
        if (data.tradeType != null) {
            message.tradeType = data.tradeType;
        }
        if (data.time != null) {
            message.time = data.time;
        }
        return message;
    }
    toObject() {
        const data: {
            price?: string;
            quantity?: string;
            tradeType?: number;
            time?: number;
        } = {};
        if (this.price != null) {
            data.price = this.price;
        }
        if (this.quantity != null) {
            data.quantity = this.quantity;
        }
        if (this.tradeType != null) {
            data.tradeType = this.tradeType;
        }
        if (this.time != null) {
            data.time = this.time;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.price.length)
            writer.writeString(1, this.price);
        if (this.quantity.length)
            writer.writeString(2, this.quantity);
        if (this.tradeType != 0)
            writer.writeInt32(3, this.tradeType);
        if (this.time != 0)
            writer.writeInt64(4, this.time);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicAggreDealsV3ApiItem {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicAggreDealsV3ApiItem();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.price = reader.readString();
                    break;
                case 2:
                    message.quantity = reader.readString();
                    break;
                case 3:
                    message.tradeType = reader.readInt32();
                    break;
                case 4:
                    message.time = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicAggreDealsV3ApiItem {
        return PublicAggreDealsV3ApiItem.deserialize(bytes);
    }
}
