/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PublicSpotKlineV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PublicSpotKlineV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        interval?: string;
        windowStart?: number;
        openingPrice?: string;
        closingPrice?: string;
        highestPrice?: string;
        lowestPrice?: string;
        volume?: string;
        amount?: string;
        windowEnd?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("interval" in data && data.interval != undefined) {
                this.interval = data.interval;
            }
            if ("windowStart" in data && data.windowStart != undefined) {
                this.windowStart = data.windowStart;
            }
            if ("openingPrice" in data && data.openingPrice != undefined) {
                this.openingPrice = data.openingPrice;
            }
            if ("closingPrice" in data && data.closingPrice != undefined) {
                this.closingPrice = data.closingPrice;
            }
            if ("highestPrice" in data && data.highestPrice != undefined) {
                this.highestPrice = data.highestPrice;
            }
            if ("lowestPrice" in data && data.lowestPrice != undefined) {
                this.lowestPrice = data.lowestPrice;
            }
            if ("volume" in data && data.volume != undefined) {
                this.volume = data.volume;
            }
            if ("amount" in data && data.amount != undefined) {
                this.amount = data.amount;
            }
            if ("windowEnd" in data && data.windowEnd != undefined) {
                this.windowEnd = data.windowEnd;
            }
        }
    }
    get interval() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set interval(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get windowStart() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set windowStart(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get openingPrice() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set openingPrice(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get closingPrice() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set closingPrice(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get highestPrice() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set highestPrice(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get lowestPrice() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set lowestPrice(value: string) {
        pb_1.Message.setField(this, 6, value);
    }
    get volume() {
        return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
    }
    set volume(value: string) {
        pb_1.Message.setField(this, 7, value);
    }
    get amount() {
        return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
    }
    set amount(value: string) {
        pb_1.Message.setField(this, 8, value);
    }
    get windowEnd() {
        return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
    }
    set windowEnd(value: number) {
        pb_1.Message.setField(this, 9, value);
    }
    static fromObject(data: {
        interval?: string;
        windowStart?: number;
        openingPrice?: string;
        closingPrice?: string;
        highestPrice?: string;
        lowestPrice?: string;
        volume?: string;
        amount?: string;
        windowEnd?: number;
    }): PublicSpotKlineV3Api {
        const message = new PublicSpotKlineV3Api({});
        if (data.interval != null) {
            message.interval = data.interval;
        }
        if (data.windowStart != null) {
            message.windowStart = data.windowStart;
        }
        if (data.openingPrice != null) {
            message.openingPrice = data.openingPrice;
        }
        if (data.closingPrice != null) {
            message.closingPrice = data.closingPrice;
        }
        if (data.highestPrice != null) {
            message.highestPrice = data.highestPrice;
        }
        if (data.lowestPrice != null) {
            message.lowestPrice = data.lowestPrice;
        }
        if (data.volume != null) {
            message.volume = data.volume;
        }
        if (data.amount != null) {
            message.amount = data.amount;
        }
        if (data.windowEnd != null) {
            message.windowEnd = data.windowEnd;
        }
        return message;
    }
    toObject() {
        const data: {
            interval?: string;
            windowStart?: number;
            openingPrice?: string;
            closingPrice?: string;
            highestPrice?: string;
            lowestPrice?: string;
            volume?: string;
            amount?: string;
            windowEnd?: number;
        } = {};
        if (this.interval != null) {
            data.interval = this.interval;
        }
        if (this.windowStart != null) {
            data.windowStart = this.windowStart;
        }
        if (this.openingPrice != null) {
            data.openingPrice = this.openingPrice;
        }
        if (this.closingPrice != null) {
            data.closingPrice = this.closingPrice;
        }
        if (this.highestPrice != null) {
            data.highestPrice = this.highestPrice;
        }
        if (this.lowestPrice != null) {
            data.lowestPrice = this.lowestPrice;
        }
        if (this.volume != null) {
            data.volume = this.volume;
        }
        if (this.amount != null) {
            data.amount = this.amount;
        }
        if (this.windowEnd != null) {
            data.windowEnd = this.windowEnd;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.interval.length)
            writer.writeString(1, this.interval);
        if (this.windowStart != 0)
            writer.writeInt64(2, this.windowStart);
        if (this.openingPrice.length)
            writer.writeString(3, this.openingPrice);
        if (this.closingPrice.length)
            writer.writeString(4, this.closingPrice);
        if (this.highestPrice.length)
            writer.writeString(5, this.highestPrice);
        if (this.lowestPrice.length)
            writer.writeString(6, this.lowestPrice);
        if (this.volume.length)
            writer.writeString(7, this.volume);
        if (this.amount.length)
            writer.writeString(8, this.amount);
        if (this.windowEnd != 0)
            writer.writeInt64(9, this.windowEnd);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicSpotKlineV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicSpotKlineV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.interval = reader.readString();
                    break;
                case 2:
                    message.windowStart = reader.readInt64();
                    break;
                case 3:
                    message.openingPrice = reader.readString();
                    break;
                case 4:
                    message.closingPrice = reader.readString();
                    break;
                case 5:
                    message.highestPrice = reader.readString();
                    break;
                case 6:
                    message.lowestPrice = reader.readString();
                    break;
                case 7:
                    message.volume = reader.readString();
                    break;
                case 8:
                    message.amount = reader.readString();
                    break;
                case 9:
                    message.windowEnd = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicSpotKlineV3Api {
        return PublicSpotKlineV3Api.deserialize(bytes);
    }
}
