/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PublicAggreBookTickerV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PublicAggreBookTickerV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        bidPrice?: string;
        bidQuantity?: string;
        askPrice?: string;
        askQuantity?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("bidPrice" in data && data.bidPrice != undefined) {
                this.bidPrice = data.bidPrice;
            }
            if ("bidQuantity" in data && data.bidQuantity != undefined) {
                this.bidQuantity = data.bidQuantity;
            }
            if ("askPrice" in data && data.askPrice != undefined) {
                this.askPrice = data.askPrice;
            }
            if ("askQuantity" in data && data.askQuantity != undefined) {
                this.askQuantity = data.askQuantity;
            }
        }
    }
    get bidPrice() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set bidPrice(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get bidQuantity() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set bidQuantity(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get askPrice() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set askPrice(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get askQuantity() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set askQuantity(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        bidPrice?: string;
        bidQuantity?: string;
        askPrice?: string;
        askQuantity?: string;
    }): PublicAggreBookTickerV3Api {
        const message = new PublicAggreBookTickerV3Api({});
        if (data.bidPrice != null) {
            message.bidPrice = data.bidPrice;
        }
        if (data.bidQuantity != null) {
            message.bidQuantity = data.bidQuantity;
        }
        if (data.askPrice != null) {
            message.askPrice = data.askPrice;
        }
        if (data.askQuantity != null) {
            message.askQuantity = data.askQuantity;
        }
        return message;
    }
    toObject() {
        const data: {
            bidPrice?: string;
            bidQuantity?: string;
            askPrice?: string;
            askQuantity?: string;
        } = {};
        if (this.bidPrice != null) {
            data.bidPrice = this.bidPrice;
        }
        if (this.bidQuantity != null) {
            data.bidQuantity = this.bidQuantity;
        }
        if (this.askPrice != null) {
            data.askPrice = this.askPrice;
        }
        if (this.askQuantity != null) {
            data.askQuantity = this.askQuantity;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.bidPrice.length)
            writer.writeString(1, this.bidPrice);
        if (this.bidQuantity.length)
            writer.writeString(2, this.bidQuantity);
        if (this.askPrice.length)
            writer.writeString(3, this.askPrice);
        if (this.askQuantity.length)
            writer.writeString(4, this.askQuantity);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicAggreBookTickerV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicAggreBookTickerV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.bidPrice = reader.readString();
                    break;
                case 2:
                    message.bidQuantity = reader.readString();
                    break;
                case 3:
                    message.askPrice = reader.readString();
                    break;
                case 4:
                    message.askQuantity = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicAggreBookTickerV3Api {
        return PublicAggreBookTickerV3Api.deserialize(bytes);
    }
}
