/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PublicMiniTickerV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PublicMiniTickerV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        symbol?: string;
        price?: string;
        rate?: string;
        zonedRate?: string;
        high?: string;
        low?: string;
        volume?: string;
        quantity?: string;
        lastCloseRate?: string;
        lastCloseZonedRate?: string;
        lastCloseHigh?: string;
        lastCloseLow?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("symbol" in data && data.symbol != undefined) {
                this.symbol = data.symbol;
            }
            if ("price" in data && data.price != undefined) {
                this.price = data.price;
            }
            if ("rate" in data && data.rate != undefined) {
                this.rate = data.rate;
            }
            if ("zonedRate" in data && data.zonedRate != undefined) {
                this.zonedRate = data.zonedRate;
            }
            if ("high" in data && data.high != undefined) {
                this.high = data.high;
            }
            if ("low" in data && data.low != undefined) {
                this.low = data.low;
            }
            if ("volume" in data && data.volume != undefined) {
                this.volume = data.volume;
            }
            if ("quantity" in data && data.quantity != undefined) {
                this.quantity = data.quantity;
            }
            if ("lastCloseRate" in data && data.lastCloseRate != undefined) {
                this.lastCloseRate = data.lastCloseRate;
            }
            if ("lastCloseZonedRate" in data && data.lastCloseZonedRate != undefined) {
                this.lastCloseZonedRate = data.lastCloseZonedRate;
            }
            if ("lastCloseHigh" in data && data.lastCloseHigh != undefined) {
                this.lastCloseHigh = data.lastCloseHigh;
            }
            if ("lastCloseLow" in data && data.lastCloseLow != undefined) {
                this.lastCloseLow = data.lastCloseLow;
            }
        }
    }
    get symbol() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set symbol(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get price() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set price(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get rate() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set rate(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get zonedRate() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set zonedRate(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get high() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set high(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    get low() {
        return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
    }
    set low(value: string) {
        pb_1.Message.setField(this, 6, value);
    }
    get volume() {
        return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
    }
    set volume(value: string) {
        pb_1.Message.setField(this, 7, value);
    }
    get quantity() {
        return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
    }
    set quantity(value: string) {
        pb_1.Message.setField(this, 8, value);
    }
    get lastCloseRate() {
        return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
    }
    set lastCloseRate(value: string) {
        pb_1.Message.setField(this, 9, value);
    }
    get lastCloseZonedRate() {
        return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
    }
    set lastCloseZonedRate(value: string) {
        pb_1.Message.setField(this, 10, value);
    }
    get lastCloseHigh() {
        return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
    }
    set lastCloseHigh(value: string) {
        pb_1.Message.setField(this, 11, value);
    }
    get lastCloseLow() {
        return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
    }
    set lastCloseLow(value: string) {
        pb_1.Message.setField(this, 12, value);
    }
    static fromObject(data: {
        symbol?: string;
        price?: string;
        rate?: string;
        zonedRate?: string;
        high?: string;
        low?: string;
        volume?: string;
        quantity?: string;
        lastCloseRate?: string;
        lastCloseZonedRate?: string;
        lastCloseHigh?: string;
        lastCloseLow?: string;
    }): PublicMiniTickerV3Api {
        const message = new PublicMiniTickerV3Api({});
        if (data.symbol != null) {
            message.symbol = data.symbol;
        }
        if (data.price != null) {
            message.price = data.price;
        }
        if (data.rate != null) {
            message.rate = data.rate;
        }
        if (data.zonedRate != null) {
            message.zonedRate = data.zonedRate;
        }
        if (data.high != null) {
            message.high = data.high;
        }
        if (data.low != null) {
            message.low = data.low;
        }
        if (data.volume != null) {
            message.volume = data.volume;
        }
        if (data.quantity != null) {
            message.quantity = data.quantity;
        }
        if (data.lastCloseRate != null) {
            message.lastCloseRate = data.lastCloseRate;
        }
        if (data.lastCloseZonedRate != null) {
            message.lastCloseZonedRate = data.lastCloseZonedRate;
        }
        if (data.lastCloseHigh != null) {
            message.lastCloseHigh = data.lastCloseHigh;
        }
        if (data.lastCloseLow != null) {
            message.lastCloseLow = data.lastCloseLow;
        }
        return message;
    }
    toObject() {
        const data: {
            symbol?: string;
            price?: string;
            rate?: string;
            zonedRate?: string;
            high?: string;
            low?: string;
            volume?: string;
            quantity?: string;
            lastCloseRate?: string;
            lastCloseZonedRate?: string;
            lastCloseHigh?: string;
            lastCloseLow?: string;
        } = {};
        if (this.symbol != null) {
            data.symbol = this.symbol;
        }
        if (this.price != null) {
            data.price = this.price;
        }
        if (this.rate != null) {
            data.rate = this.rate;
        }
        if (this.zonedRate != null) {
            data.zonedRate = this.zonedRate;
        }
        if (this.high != null) {
            data.high = this.high;
        }
        if (this.low != null) {
            data.low = this.low;
        }
        if (this.volume != null) {
            data.volume = this.volume;
        }
        if (this.quantity != null) {
            data.quantity = this.quantity;
        }
        if (this.lastCloseRate != null) {
            data.lastCloseRate = this.lastCloseRate;
        }
        if (this.lastCloseZonedRate != null) {
            data.lastCloseZonedRate = this.lastCloseZonedRate;
        }
        if (this.lastCloseHigh != null) {
            data.lastCloseHigh = this.lastCloseHigh;
        }
        if (this.lastCloseLow != null) {
            data.lastCloseLow = this.lastCloseLow;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.symbol.length)
            writer.writeString(1, this.symbol);
        if (this.price.length)
            writer.writeString(2, this.price);
        if (this.rate.length)
            writer.writeString(3, this.rate);
        if (this.zonedRate.length)
            writer.writeString(4, this.zonedRate);
        if (this.high.length)
            writer.writeString(5, this.high);
        if (this.low.length)
            writer.writeString(6, this.low);
        if (this.volume.length)
            writer.writeString(7, this.volume);
        if (this.quantity.length)
            writer.writeString(8, this.quantity);
        if (this.lastCloseRate.length)
            writer.writeString(9, this.lastCloseRate);
        if (this.lastCloseZonedRate.length)
            writer.writeString(10, this.lastCloseZonedRate);
        if (this.lastCloseHigh.length)
            writer.writeString(11, this.lastCloseHigh);
        if (this.lastCloseLow.length)
            writer.writeString(12, this.lastCloseLow);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicMiniTickerV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicMiniTickerV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.symbol = reader.readString();
                    break;
                case 2:
                    message.price = reader.readString();
                    break;
                case 3:
                    message.rate = reader.readString();
                    break;
                case 4:
                    message.zonedRate = reader.readString();
                    break;
                case 5:
                    message.high = reader.readString();
                    break;
                case 6:
                    message.low = reader.readString();
                    break;
                case 7:
                    message.volume = reader.readString();
                    break;
                case 8:
                    message.quantity = reader.readString();
                    break;
                case 9:
                    message.lastCloseRate = reader.readString();
                    break;
                case 10:
                    message.lastCloseZonedRate = reader.readString();
                    break;
                case 11:
                    message.lastCloseHigh = reader.readString();
                    break;
                case 12:
                    message.lastCloseLow = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicMiniTickerV3Api {
        return PublicMiniTickerV3Api.deserialize(bytes);
    }
}
