/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PublicIncreaseDepthsBatchV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./PublicIncreaseDepthsV3Api.ts";
import * as pb_1 from "google-protobuf";
export class PublicIncreaseDepthsBatchV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        items?: dependency_1.PublicIncreaseDepthsV3Api[];
        eventType?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("items" in data && data.items != undefined) {
                this.items = data.items;
            }
            if ("eventType" in data && data.eventType != undefined) {
                this.eventType = data.eventType;
            }
        }
    }
    get items() {
        return pb_1.Message.getRepeatedWrapperField(this, dependency_1.PublicIncreaseDepthsV3Api, 1) as dependency_1.PublicIncreaseDepthsV3Api[];
    }
    set items(value: dependency_1.PublicIncreaseDepthsV3Api[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    get eventType() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set eventType(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        items?: ReturnType<typeof dependency_1.PublicIncreaseDepthsV3Api.prototype.toObject>[];
        eventType?: string;
    }): PublicIncreaseDepthsBatchV3Api {
        const message = new PublicIncreaseDepthsBatchV3Api({});
        if (data.items != null) {
            message.items = data.items.map(item => dependency_1.PublicIncreaseDepthsV3Api.fromObject(item));
        }
        if (data.eventType != null) {
            message.eventType = data.eventType;
        }
        return message;
    }
    toObject() {
        const data: {
            items?: ReturnType<typeof dependency_1.PublicIncreaseDepthsV3Api.prototype.toObject>[];
            eventType?: string;
        } = {};
        if (this.items != null) {
            data.items = this.items.map((item: dependency_1.PublicIncreaseDepthsV3Api) => item.toObject());
        }
        if (this.eventType != null) {
            data.eventType = this.eventType;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.items.length)
            writer.writeRepeatedMessage(1, this.items, (item: dependency_1.PublicIncreaseDepthsV3Api) => item.serialize(writer));
        if (this.eventType.length)
            writer.writeString(2, this.eventType);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicIncreaseDepthsBatchV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicIncreaseDepthsBatchV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.items, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_1.PublicIncreaseDepthsV3Api.deserialize(reader), dependency_1.PublicIncreaseDepthsV3Api));
                    break;
                case 2:
                    message.eventType = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicIncreaseDepthsBatchV3Api {
        return PublicIncreaseDepthsBatchV3Api.deserialize(bytes);
    }
}
