/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PublicAggreDepthsV3Api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class PublicAggreDepthsV3Api extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        asks?: PublicAggreDepthV3ApiItem[];
        bids?: PublicAggreDepthV3ApiItem[];
        eventType?: string;
        fromVersion?: string;
        toVersion?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1, 2], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("asks" in data && data.asks != undefined) {
                this.asks = data.asks;
            }
            if ("bids" in data && data.bids != undefined) {
                this.bids = data.bids;
            }
            if ("eventType" in data && data.eventType != undefined) {
                this.eventType = data.eventType;
            }
            if ("fromVersion" in data && data.fromVersion != undefined) {
                this.fromVersion = data.fromVersion;
            }
            if ("toVersion" in data && data.toVersion != undefined) {
                this.toVersion = data.toVersion;
            }
        }
    }
    get asks() {
        return pb_1.Message.getRepeatedWrapperField(this, PublicAggreDepthV3ApiItem, 1) as PublicAggreDepthV3ApiItem[];
    }
    set asks(value: PublicAggreDepthV3ApiItem[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    get bids() {
        return pb_1.Message.getRepeatedWrapperField(this, PublicAggreDepthV3ApiItem, 2) as PublicAggreDepthV3ApiItem[];
    }
    set bids(value: PublicAggreDepthV3ApiItem[]) {
        pb_1.Message.setRepeatedWrapperField(this, 2, value);
    }
    get eventType() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set eventType(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get fromVersion() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set fromVersion(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get toVersion() {
        return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
    }
    set toVersion(value: string) {
        pb_1.Message.setField(this, 5, value);
    }
    static fromObject(data: {
        asks?: ReturnType<typeof PublicAggreDepthV3ApiItem.prototype.toObject>[];
        bids?: ReturnType<typeof PublicAggreDepthV3ApiItem.prototype.toObject>[];
        eventType?: string;
        fromVersion?: string;
        toVersion?: string;
    }): PublicAggreDepthsV3Api {
        const message = new PublicAggreDepthsV3Api({});
        if (data.asks != null) {
            message.asks = data.asks.map(item => PublicAggreDepthV3ApiItem.fromObject(item));
        }
        if (data.bids != null) {
            message.bids = data.bids.map(item => PublicAggreDepthV3ApiItem.fromObject(item));
        }
        if (data.eventType != null) {
            message.eventType = data.eventType;
        }
        if (data.fromVersion != null) {
            message.fromVersion = data.fromVersion;
        }
        if (data.toVersion != null) {
            message.toVersion = data.toVersion;
        }
        return message;
    }
    toObject() {
        const data: {
            asks?: ReturnType<typeof PublicAggreDepthV3ApiItem.prototype.toObject>[];
            bids?: ReturnType<typeof PublicAggreDepthV3ApiItem.prototype.toObject>[];
            eventType?: string;
            fromVersion?: string;
            toVersion?: string;
        } = {};
        if (this.asks != null) {
            data.asks = this.asks.map((item: PublicAggreDepthV3ApiItem) => item.toObject());
        }
        if (this.bids != null) {
            data.bids = this.bids.map((item: PublicAggreDepthV3ApiItem) => item.toObject());
        }
        if (this.eventType != null) {
            data.eventType = this.eventType;
        }
        if (this.fromVersion != null) {
            data.fromVersion = this.fromVersion;
        }
        if (this.toVersion != null) {
            data.toVersion = this.toVersion;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.asks.length)
            writer.writeRepeatedMessage(1, this.asks, (item: PublicAggreDepthV3ApiItem) => item.serialize(writer));
        if (this.bids.length)
            writer.writeRepeatedMessage(2, this.bids, (item: PublicAggreDepthV3ApiItem) => item.serialize(writer));
        if (this.eventType.length)
            writer.writeString(3, this.eventType);
        if (this.fromVersion.length)
            writer.writeString(4, this.fromVersion);
        if (this.toVersion.length)
            writer.writeString(5, this.toVersion);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicAggreDepthsV3Api {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicAggreDepthsV3Api();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.asks, () => pb_1.Message.addToRepeatedWrapperField(message, 1, PublicAggreDepthV3ApiItem.deserialize(reader), PublicAggreDepthV3ApiItem));
                    break;
                case 2:
                    reader.readMessage(message.bids, () => pb_1.Message.addToRepeatedWrapperField(message, 2, PublicAggreDepthV3ApiItem.deserialize(reader), PublicAggreDepthV3ApiItem));
                    break;
                case 3:
                    message.eventType = reader.readString();
                    break;
                case 4:
                    message.fromVersion = reader.readString();
                    break;
                case 5:
                    message.toVersion = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicAggreDepthsV3Api {
        return PublicAggreDepthsV3Api.deserialize(bytes);
    }
}
export class PublicAggreDepthV3ApiItem extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        price?: string;
        quantity?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("price" in data && data.price != undefined) {
                this.price = data.price;
            }
            if ("quantity" in data && data.quantity != undefined) {
                this.quantity = data.quantity;
            }
        }
    }
    get price() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set price(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get quantity() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set quantity(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        price?: string;
        quantity?: string;
    }): PublicAggreDepthV3ApiItem {
        const message = new PublicAggreDepthV3ApiItem({});
        if (data.price != null) {
            message.price = data.price;
        }
        if (data.quantity != null) {
            message.quantity = data.quantity;
        }
        return message;
    }
    toObject() {
        const data: {
            price?: string;
            quantity?: string;
        } = {};
        if (this.price != null) {
            data.price = this.price;
        }
        if (this.quantity != null) {
            data.quantity = this.quantity;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.price.length)
            writer.writeString(1, this.price);
        if (this.quantity.length)
            writer.writeString(2, this.quantity);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicAggreDepthV3ApiItem {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PublicAggreDepthV3ApiItem();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.price = reader.readString();
                    break;
                case 2:
                    message.quantity = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PublicAggreDepthV3ApiItem {
        return PublicAggreDepthV3ApiItem.deserialize(bytes);
    }
}
