/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.1
 * source: PushDataV3ApiWrapper.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./PublicDealsV3Api.ts";
import * as dependency_2 from "./PublicIncreaseDepthsV3Api.ts";
import * as dependency_3 from "./PublicLimitDepthsV3Api.ts";
import * as dependency_4 from "./PrivateOrdersV3Api.ts";
import * as dependency_5 from "./PublicBookTickerV3Api.ts";
import * as dependency_6 from "./PrivateDealsV3Api.ts";
import * as dependency_7 from "./PrivateAccountV3Api.ts";
import * as dependency_8 from "./PublicSpotKlineV3Api.ts";
import * as dependency_9 from "./PublicMiniTickerV3Api.ts";
import * as dependency_10 from "./PublicMiniTickersV3Api.ts";
import * as dependency_11 from "./PublicBookTickerBatchV3Api.ts";
import * as dependency_12 from "./PublicIncreaseDepthsBatchV3Api.ts";
import * as dependency_13 from "./PublicAggreDepthsV3Api.ts";
import * as dependency_14 from "./PublicAggreDealsV3Api.ts";
import * as dependency_15 from "./PublicAggreBookTickerV3Api.ts";
import * as pb_1 from "google-protobuf";
export class PushDataV3ApiWrapper extends pb_1.Message {
    #one_of_decls: number[][] = [[301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315], [3], [4], [5], [6]];
    constructor(data?: any[] | ({
        channel?: string;
    } & (({
        publicDeals?: dependency_1.PublicDealsV3Api;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: dependency_2.PublicIncreaseDepthsV3Api;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: dependency_3.PublicLimitDepthsV3Api;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: dependency_4.PrivateOrdersV3Api;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: dependency_5.PublicBookTickerV3Api;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: dependency_6.PrivateDealsV3Api;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: dependency_7.PrivateAccountV3Api;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: dependency_8.PublicSpotKlineV3Api;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: dependency_9.PublicMiniTickerV3Api;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: dependency_10.PublicMiniTickersV3Api;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: dependency_11.PublicBookTickerBatchV3Api;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: dependency_12.PublicIncreaseDepthsBatchV3Api;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: dependency_13.PublicAggreDepthsV3Api;
        publicAggreDeals?: never;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: dependency_14.PublicAggreDealsV3Api;
        publicAggreBookTicker?: never;
    } | {
        publicDeals?: never;
        publicIncreaseDepths?: never;
        publicLimitDepths?: never;
        privateOrders?: never;
        publicBookTicker?: never;
        privateDeals?: never;
        privateAccount?: never;
        publicSpotKline?: never;
        publicMiniTicker?: never;
        publicMiniTickers?: never;
        publicBookTickerBatch?: never;
        publicIncreaseDepthsBatch?: never;
        publicAggreDepths?: never;
        publicAggreDeals?: never;
        publicAggreBookTicker?: dependency_15.PublicAggreBookTickerV3Api;
    }) | ({
        symbol?: string;
    }) | ({
        symbolId?: string;
    }) | ({
        createTime?: number;
    }) | ({
        sendTime?: number;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("channel" in data && data.channel != undefined) {
                this.channel = data.channel;
            }
            if ("publicDeals" in data && data.publicDeals != undefined) {
                this.publicDeals = data.publicDeals;
            }
            if ("publicIncreaseDepths" in data && data.publicIncreaseDepths != undefined) {
                this.publicIncreaseDepths = data.publicIncreaseDepths;
            }
            if ("publicLimitDepths" in data && data.publicLimitDepths != undefined) {
                this.publicLimitDepths = data.publicLimitDepths;
            }
            if ("privateOrders" in data && data.privateOrders != undefined) {
                this.privateOrders = data.privateOrders;
            }
            if ("publicBookTicker" in data && data.publicBookTicker != undefined) {
                this.publicBookTicker = data.publicBookTicker;
            }
            if ("privateDeals" in data && data.privateDeals != undefined) {
                this.privateDeals = data.privateDeals;
            }
            if ("privateAccount" in data && data.privateAccount != undefined) {
                this.privateAccount = data.privateAccount;
            }
            if ("publicSpotKline" in data && data.publicSpotKline != undefined) {
                this.publicSpotKline = data.publicSpotKline;
            }
            if ("publicMiniTicker" in data && data.publicMiniTicker != undefined) {
                this.publicMiniTicker = data.publicMiniTicker;
            }
            if ("publicMiniTickers" in data && data.publicMiniTickers != undefined) {
                this.publicMiniTickers = data.publicMiniTickers;
            }
            if ("publicBookTickerBatch" in data && data.publicBookTickerBatch != undefined) {
                this.publicBookTickerBatch = data.publicBookTickerBatch;
            }
            if ("publicIncreaseDepthsBatch" in data && data.publicIncreaseDepthsBatch != undefined) {
                this.publicIncreaseDepthsBatch = data.publicIncreaseDepthsBatch;
            }
            if ("publicAggreDepths" in data && data.publicAggreDepths != undefined) {
                this.publicAggreDepths = data.publicAggreDepths;
            }
            if ("publicAggreDeals" in data && data.publicAggreDeals != undefined) {
                this.publicAggreDeals = data.publicAggreDeals;
            }
            if ("publicAggreBookTicker" in data && data.publicAggreBookTicker != undefined) {
                this.publicAggreBookTicker = data.publicAggreBookTicker;
            }
            if ("symbol" in data && data.symbol != undefined) {
                this.symbol = data.symbol;
            }
            if ("symbolId" in data && data.symbolId != undefined) {
                this.symbolId = data.symbolId;
            }
            if ("createTime" in data && data.createTime != undefined) {
                this.createTime = data.createTime;
            }
            if ("sendTime" in data && data.sendTime != undefined) {
                this.sendTime = data.sendTime;
            }
        }
    }
    get channel() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set channel(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get publicDeals() {
        return pb_1.Message.getWrapperField(this, dependency_1.PublicDealsV3Api, 301) as dependency_1.PublicDealsV3Api;
    }
    set publicDeals(value: dependency_1.PublicDealsV3Api) {
        pb_1.Message.setOneofWrapperField(this, 301, this.#one_of_decls[0], value);
    }
    get has_publicDeals() {
        return pb_1.Message.getField(this, 301) != null;
    }
    get publicIncreaseDepths() {
        return pb_1.Message.getWrapperField(this, dependency_2.PublicIncreaseDepthsV3Api, 302) as dependency_2.PublicIncreaseDepthsV3Api;
    }
    set publicIncreaseDepths(value: dependency_2.PublicIncreaseDepthsV3Api) {
        pb_1.Message.setOneofWrapperField(this, 302, this.#one_of_decls[0], value);
    }
    get has_publicIncreaseDepths() {
        return pb_1.Message.getField(this, 302) != null;
    }
    get publicLimitDepths() {
        return pb_1.Message.getWrapperField(this, dependency_3.PublicLimitDepthsV3Api, 303) as dependency_3.PublicLimitDepthsV3Api;
    }
    set publicLimitDepths(value: dependency_3.PublicLimitDepthsV3Api) {
        pb_1.Message.setOneofWrapperField(this, 303, this.#one_of_decls[0], value);
    }
    get has_publicLimitDepths() {
        return pb_1.Message.getField(this, 303) != null;
    }
    get privateOrders() {
        return pb_1.Message.getWrapperField(this, dependency_4.PrivateOrdersV3Api, 304) as dependency_4.PrivateOrdersV3Api;
    }
    set privateOrders(value: dependency_4.PrivateOrdersV3Api) {
        pb_1.Message.setOneofWrapperField(this, 304, this.#one_of_decls[0], value);
    }
    get has_privateOrders() {
        return pb_1.Message.getField(this, 304) != null;
    }
    get publicBookTicker() {
        return pb_1.Message.getWrapperField(this, dependency_5.PublicBookTickerV3Api, 305) as dependency_5.PublicBookTickerV3Api;
    }
    set publicBookTicker(value: dependency_5.PublicBookTickerV3Api) {
        pb_1.Message.setOneofWrapperField(this, 305, this.#one_of_decls[0], value);
    }
    get has_publicBookTicker() {
        return pb_1.Message.getField(this, 305) != null;
    }
    get privateDeals() {
        return pb_1.Message.getWrapperField(this, dependency_6.PrivateDealsV3Api, 306) as dependency_6.PrivateDealsV3Api;
    }
    set privateDeals(value: dependency_6.PrivateDealsV3Api) {
        pb_1.Message.setOneofWrapperField(this, 306, this.#one_of_decls[0], value);
    }
    get has_privateDeals() {
        return pb_1.Message.getField(this, 306) != null;
    }
    get privateAccount() {
        return pb_1.Message.getWrapperField(this, dependency_7.PrivateAccountV3Api, 307) as dependency_7.PrivateAccountV3Api;
    }
    set privateAccount(value: dependency_7.PrivateAccountV3Api) {
        pb_1.Message.setOneofWrapperField(this, 307, this.#one_of_decls[0], value);
    }
    get has_privateAccount() {
        return pb_1.Message.getField(this, 307) != null;
    }
    get publicSpotKline() {
        return pb_1.Message.getWrapperField(this, dependency_8.PublicSpotKlineV3Api, 308) as dependency_8.PublicSpotKlineV3Api;
    }
    set publicSpotKline(value: dependency_8.PublicSpotKlineV3Api) {
        pb_1.Message.setOneofWrapperField(this, 308, this.#one_of_decls[0], value);
    }
    get has_publicSpotKline() {
        return pb_1.Message.getField(this, 308) != null;
    }
    get publicMiniTicker() {
        return pb_1.Message.getWrapperField(this, dependency_9.PublicMiniTickerV3Api, 309) as dependency_9.PublicMiniTickerV3Api;
    }
    set publicMiniTicker(value: dependency_9.PublicMiniTickerV3Api) {
        pb_1.Message.setOneofWrapperField(this, 309, this.#one_of_decls[0], value);
    }
    get has_publicMiniTicker() {
        return pb_1.Message.getField(this, 309) != null;
    }
    get publicMiniTickers() {
        return pb_1.Message.getWrapperField(this, dependency_10.PublicMiniTickersV3Api, 310) as dependency_10.PublicMiniTickersV3Api;
    }
    set publicMiniTickers(value: dependency_10.PublicMiniTickersV3Api) {
        pb_1.Message.setOneofWrapperField(this, 310, this.#one_of_decls[0], value);
    }
    get has_publicMiniTickers() {
        return pb_1.Message.getField(this, 310) != null;
    }
    get publicBookTickerBatch() {
        return pb_1.Message.getWrapperField(this, dependency_11.PublicBookTickerBatchV3Api, 311) as dependency_11.PublicBookTickerBatchV3Api;
    }
    set publicBookTickerBatch(value: dependency_11.PublicBookTickerBatchV3Api) {
        pb_1.Message.setOneofWrapperField(this, 311, this.#one_of_decls[0], value);
    }
    get has_publicBookTickerBatch() {
        return pb_1.Message.getField(this, 311) != null;
    }
    get publicIncreaseDepthsBatch() {
        return pb_1.Message.getWrapperField(this, dependency_12.PublicIncreaseDepthsBatchV3Api, 312) as dependency_12.PublicIncreaseDepthsBatchV3Api;
    }
    set publicIncreaseDepthsBatch(value: dependency_12.PublicIncreaseDepthsBatchV3Api) {
        pb_1.Message.setOneofWrapperField(this, 312, this.#one_of_decls[0], value);
    }
    get has_publicIncreaseDepthsBatch() {
        return pb_1.Message.getField(this, 312) != null;
    }
    get publicAggreDepths() {
        return pb_1.Message.getWrapperField(this, dependency_13.PublicAggreDepthsV3Api, 313) as dependency_13.PublicAggreDepthsV3Api;
    }
    set publicAggreDepths(value: dependency_13.PublicAggreDepthsV3Api) {
        pb_1.Message.setOneofWrapperField(this, 313, this.#one_of_decls[0], value);
    }
    get has_publicAggreDepths() {
        return pb_1.Message.getField(this, 313) != null;
    }
    get publicAggreDeals() {
        return pb_1.Message.getWrapperField(this, dependency_14.PublicAggreDealsV3Api, 314) as dependency_14.PublicAggreDealsV3Api;
    }
    set publicAggreDeals(value: dependency_14.PublicAggreDealsV3Api) {
        pb_1.Message.setOneofWrapperField(this, 314, this.#one_of_decls[0], value);
    }
    get has_publicAggreDeals() {
        return pb_1.Message.getField(this, 314) != null;
    }
    get publicAggreBookTicker() {
        return pb_1.Message.getWrapperField(this, dependency_15.PublicAggreBookTickerV3Api, 315) as dependency_15.PublicAggreBookTickerV3Api;
    }
    set publicAggreBookTicker(value: dependency_15.PublicAggreBookTickerV3Api) {
        pb_1.Message.setOneofWrapperField(this, 315, this.#one_of_decls[0], value);
    }
    get has_publicAggreBookTicker() {
        return pb_1.Message.getField(this, 315) != null;
    }
    get symbol() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set symbol(value: string) {
        pb_1.Message.setOneofField(this, 3, this.#one_of_decls[1], value);
    }
    get has_symbol() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get symbolId() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set symbolId(value: string) {
        pb_1.Message.setOneofField(this, 4, this.#one_of_decls[2], value);
    }
    get has_symbolId() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get createTime() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set createTime(value: number) {
        pb_1.Message.setOneofField(this, 5, this.#one_of_decls[3], value);
    }
    get has_createTime() {
        return pb_1.Message.getField(this, 5) != null;
    }
    get sendTime() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set sendTime(value: number) {
        pb_1.Message.setOneofField(this, 6, this.#one_of_decls[4], value);
    }
    get has_sendTime() {
        return pb_1.Message.getField(this, 6) != null;
    }
    get body() {
        const cases: {
            [index: number]: "none" | "publicDeals" | "publicIncreaseDepths" | "publicLimitDepths" | "privateOrders" | "publicBookTicker" | "privateDeals" | "privateAccount" | "publicSpotKline" | "publicMiniTicker" | "publicMiniTickers" | "publicBookTickerBatch" | "publicIncreaseDepthsBatch" | "publicAggreDepths" | "publicAggreDeals" | "publicAggreBookTicker";
        } = {
            0: "none",
            301: "publicDeals",
            302: "publicIncreaseDepths",
            303: "publicLimitDepths",
            304: "privateOrders",
            305: "publicBookTicker",
            306: "privateDeals",
            307: "privateAccount",
            308: "publicSpotKline",
            309: "publicMiniTicker",
            310: "publicMiniTickers",
            311: "publicBookTickerBatch",
            312: "publicIncreaseDepthsBatch",
            313: "publicAggreDepths",
            314: "publicAggreDeals",
            315: "publicAggreBookTicker"
        };
        return cases[pb_1.Message.computeOneofCase(this, [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315])];
    }
    get _symbol() {
        const cases: {
            [index: number]: "none" | "symbol";
        } = {
            0: "none",
            3: "symbol"
        };
        return cases[pb_1.Message.computeOneofCase(this, [3])];
    }
    get _symbolId() {
        const cases: {
            [index: number]: "none" | "symbolId";
        } = {
            0: "none",
            4: "symbolId"
        };
        return cases[pb_1.Message.computeOneofCase(this, [4])];
    }
    get _createTime() {
        const cases: {
            [index: number]: "none" | "createTime";
        } = {
            0: "none",
            5: "createTime"
        };
        return cases[pb_1.Message.computeOneofCase(this, [5])];
    }
    get _sendTime() {
        const cases: {
            [index: number]: "none" | "sendTime";
        } = {
            0: "none",
            6: "sendTime"
        };
        return cases[pb_1.Message.computeOneofCase(this, [6])];
    }
    static fromObject(data: {
        channel?: string;
        publicDeals?: ReturnType<typeof dependency_1.PublicDealsV3Api.prototype.toObject>;
        publicIncreaseDepths?: ReturnType<typeof dependency_2.PublicIncreaseDepthsV3Api.prototype.toObject>;
        publicLimitDepths?: ReturnType<typeof dependency_3.PublicLimitDepthsV3Api.prototype.toObject>;
        privateOrders?: ReturnType<typeof dependency_4.PrivateOrdersV3Api.prototype.toObject>;
        publicBookTicker?: ReturnType<typeof dependency_5.PublicBookTickerV3Api.prototype.toObject>;
        privateDeals?: ReturnType<typeof dependency_6.PrivateDealsV3Api.prototype.toObject>;
        privateAccount?: ReturnType<typeof dependency_7.PrivateAccountV3Api.prototype.toObject>;
        publicSpotKline?: ReturnType<typeof dependency_8.PublicSpotKlineV3Api.prototype.toObject>;
        publicMiniTicker?: ReturnType<typeof dependency_9.PublicMiniTickerV3Api.prototype.toObject>;
        publicMiniTickers?: ReturnType<typeof dependency_10.PublicMiniTickersV3Api.prototype.toObject>;
        publicBookTickerBatch?: ReturnType<typeof dependency_11.PublicBookTickerBatchV3Api.prototype.toObject>;
        publicIncreaseDepthsBatch?: ReturnType<typeof dependency_12.PublicIncreaseDepthsBatchV3Api.prototype.toObject>;
        publicAggreDepths?: ReturnType<typeof dependency_13.PublicAggreDepthsV3Api.prototype.toObject>;
        publicAggreDeals?: ReturnType<typeof dependency_14.PublicAggreDealsV3Api.prototype.toObject>;
        publicAggreBookTicker?: ReturnType<typeof dependency_15.PublicAggreBookTickerV3Api.prototype.toObject>;
        symbol?: string;
        symbolId?: string;
        createTime?: number;
        sendTime?: number;
    }): PushDataV3ApiWrapper {
        const message = new PushDataV3ApiWrapper({});
        if (data.channel != null) {
            message.channel = data.channel;
        }
        if (data.publicDeals != null) {
            message.publicDeals = dependency_1.PublicDealsV3Api.fromObject(data.publicDeals);
        }
        if (data.publicIncreaseDepths != null) {
            message.publicIncreaseDepths = dependency_2.PublicIncreaseDepthsV3Api.fromObject(data.publicIncreaseDepths);
        }
        if (data.publicLimitDepths != null) {
            message.publicLimitDepths = dependency_3.PublicLimitDepthsV3Api.fromObject(data.publicLimitDepths);
        }
        if (data.privateOrders != null) {
            message.privateOrders = dependency_4.PrivateOrdersV3Api.fromObject(data.privateOrders);
        }
        if (data.publicBookTicker != null) {
            message.publicBookTicker = dependency_5.PublicBookTickerV3Api.fromObject(data.publicBookTicker);
        }
        if (data.privateDeals != null) {
            message.privateDeals = dependency_6.PrivateDealsV3Api.fromObject(data.privateDeals);
        }
        if (data.privateAccount != null) {
            message.privateAccount = dependency_7.PrivateAccountV3Api.fromObject(data.privateAccount);
        }
        if (data.publicSpotKline != null) {
            message.publicSpotKline = dependency_8.PublicSpotKlineV3Api.fromObject(data.publicSpotKline);
        }
        if (data.publicMiniTicker != null) {
            message.publicMiniTicker = dependency_9.PublicMiniTickerV3Api.fromObject(data.publicMiniTicker);
        }
        if (data.publicMiniTickers != null) {
            message.publicMiniTickers = dependency_10.PublicMiniTickersV3Api.fromObject(data.publicMiniTickers);
        }
        if (data.publicBookTickerBatch != null) {
            message.publicBookTickerBatch = dependency_11.PublicBookTickerBatchV3Api.fromObject(data.publicBookTickerBatch);
        }
        if (data.publicIncreaseDepthsBatch != null) {
            message.publicIncreaseDepthsBatch = dependency_12.PublicIncreaseDepthsBatchV3Api.fromObject(data.publicIncreaseDepthsBatch);
        }
        if (data.publicAggreDepths != null) {
            message.publicAggreDepths = dependency_13.PublicAggreDepthsV3Api.fromObject(data.publicAggreDepths);
        }
        if (data.publicAggreDeals != null) {
            message.publicAggreDeals = dependency_14.PublicAggreDealsV3Api.fromObject(data.publicAggreDeals);
        }
        if (data.publicAggreBookTicker != null) {
            message.publicAggreBookTicker = dependency_15.PublicAggreBookTickerV3Api.fromObject(data.publicAggreBookTicker);
        }
        if (data.symbol != null) {
            message.symbol = data.symbol;
        }
        if (data.symbolId != null) {
            message.symbolId = data.symbolId;
        }
        if (data.createTime != null) {
            message.createTime = data.createTime;
        }
        if (data.sendTime != null) {
            message.sendTime = data.sendTime;
        }
        return message;
    }
    toObject() {
        const data: {
            channel?: string;
            publicDeals?: ReturnType<typeof dependency_1.PublicDealsV3Api.prototype.toObject>;
            publicIncreaseDepths?: ReturnType<typeof dependency_2.PublicIncreaseDepthsV3Api.prototype.toObject>;
            publicLimitDepths?: ReturnType<typeof dependency_3.PublicLimitDepthsV3Api.prototype.toObject>;
            privateOrders?: ReturnType<typeof dependency_4.PrivateOrdersV3Api.prototype.toObject>;
            publicBookTicker?: ReturnType<typeof dependency_5.PublicBookTickerV3Api.prototype.toObject>;
            privateDeals?: ReturnType<typeof dependency_6.PrivateDealsV3Api.prototype.toObject>;
            privateAccount?: ReturnType<typeof dependency_7.PrivateAccountV3Api.prototype.toObject>;
            publicSpotKline?: ReturnType<typeof dependency_8.PublicSpotKlineV3Api.prototype.toObject>;
            publicMiniTicker?: ReturnType<typeof dependency_9.PublicMiniTickerV3Api.prototype.toObject>;
            publicMiniTickers?: ReturnType<typeof dependency_10.PublicMiniTickersV3Api.prototype.toObject>;
            publicBookTickerBatch?: ReturnType<typeof dependency_11.PublicBookTickerBatchV3Api.prototype.toObject>;
            publicIncreaseDepthsBatch?: ReturnType<typeof dependency_12.PublicIncreaseDepthsBatchV3Api.prototype.toObject>;
            publicAggreDepths?: ReturnType<typeof dependency_13.PublicAggreDepthsV3Api.prototype.toObject>;
            publicAggreDeals?: ReturnType<typeof dependency_14.PublicAggreDealsV3Api.prototype.toObject>;
            publicAggreBookTicker?: ReturnType<typeof dependency_15.PublicAggreBookTickerV3Api.prototype.toObject>;
            symbol?: string;
            symbolId?: string;
            createTime?: number;
            sendTime?: number;
        } = {};
        if (this.channel != null) {
            data.channel = this.channel;
        }
        if (this.publicDeals != null) {
            data.publicDeals = this.publicDeals.toObject();
        }
        if (this.publicIncreaseDepths != null) {
            data.publicIncreaseDepths = this.publicIncreaseDepths.toObject();
        }
        if (this.publicLimitDepths != null) {
            data.publicLimitDepths = this.publicLimitDepths.toObject();
        }
        if (this.privateOrders != null) {
            data.privateOrders = this.privateOrders.toObject();
        }
        if (this.publicBookTicker != null) {
            data.publicBookTicker = this.publicBookTicker.toObject();
        }
        if (this.privateDeals != null) {
            data.privateDeals = this.privateDeals.toObject();
        }
        if (this.privateAccount != null) {
            data.privateAccount = this.privateAccount.toObject();
        }
        if (this.publicSpotKline != null) {
            data.publicSpotKline = this.publicSpotKline.toObject();
        }
        if (this.publicMiniTicker != null) {
            data.publicMiniTicker = this.publicMiniTicker.toObject();
        }
        if (this.publicMiniTickers != null) {
            data.publicMiniTickers = this.publicMiniTickers.toObject();
        }
        if (this.publicBookTickerBatch != null) {
            data.publicBookTickerBatch = this.publicBookTickerBatch.toObject();
        }
        if (this.publicIncreaseDepthsBatch != null) {
            data.publicIncreaseDepthsBatch = this.publicIncreaseDepthsBatch.toObject();
        }
        if (this.publicAggreDepths != null) {
            data.publicAggreDepths = this.publicAggreDepths.toObject();
        }
        if (this.publicAggreDeals != null) {
            data.publicAggreDeals = this.publicAggreDeals.toObject();
        }
        if (this.publicAggreBookTicker != null) {
            data.publicAggreBookTicker = this.publicAggreBookTicker.toObject();
        }
        if (this.symbol != null) {
            data.symbol = this.symbol;
        }
        if (this.symbolId != null) {
            data.symbolId = this.symbolId;
        }
        if (this.createTime != null) {
            data.createTime = this.createTime;
        }
        if (this.sendTime != null) {
            data.sendTime = this.sendTime;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.channel.length)
            writer.writeString(1, this.channel);
        if (this.has_publicDeals)
            writer.writeMessage(301, this.publicDeals, () => this.publicDeals.serialize(writer));
        if (this.has_publicIncreaseDepths)
            writer.writeMessage(302, this.publicIncreaseDepths, () => this.publicIncreaseDepths.serialize(writer));
        if (this.has_publicLimitDepths)
            writer.writeMessage(303, this.publicLimitDepths, () => this.publicLimitDepths.serialize(writer));
        if (this.has_privateOrders)
            writer.writeMessage(304, this.privateOrders, () => this.privateOrders.serialize(writer));
        if (this.has_publicBookTicker)
            writer.writeMessage(305, this.publicBookTicker, () => this.publicBookTicker.serialize(writer));
        if (this.has_privateDeals)
            writer.writeMessage(306, this.privateDeals, () => this.privateDeals.serialize(writer));
        if (this.has_privateAccount)
            writer.writeMessage(307, this.privateAccount, () => this.privateAccount.serialize(writer));
        if (this.has_publicSpotKline)
            writer.writeMessage(308, this.publicSpotKline, () => this.publicSpotKline.serialize(writer));
        if (this.has_publicMiniTicker)
            writer.writeMessage(309, this.publicMiniTicker, () => this.publicMiniTicker.serialize(writer));
        if (this.has_publicMiniTickers)
            writer.writeMessage(310, this.publicMiniTickers, () => this.publicMiniTickers.serialize(writer));
        if (this.has_publicBookTickerBatch)
            writer.writeMessage(311, this.publicBookTickerBatch, () => this.publicBookTickerBatch.serialize(writer));
        if (this.has_publicIncreaseDepthsBatch)
            writer.writeMessage(312, this.publicIncreaseDepthsBatch, () => this.publicIncreaseDepthsBatch.serialize(writer));
        if (this.has_publicAggreDepths)
            writer.writeMessage(313, this.publicAggreDepths, () => this.publicAggreDepths.serialize(writer));
        if (this.has_publicAggreDeals)
            writer.writeMessage(314, this.publicAggreDeals, () => this.publicAggreDeals.serialize(writer));
        if (this.has_publicAggreBookTicker)
            writer.writeMessage(315, this.publicAggreBookTicker, () => this.publicAggreBookTicker.serialize(writer));
        if (this.has_symbol)
            writer.writeString(3, this.symbol);
        if (this.has_symbolId)
            writer.writeString(4, this.symbolId);
        if (this.has_createTime)
            writer.writeInt64(5, this.createTime);
        if (this.has_sendTime)
            writer.writeInt64(6, this.sendTime);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PushDataV3ApiWrapper {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PushDataV3ApiWrapper();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.channel = reader.readString();
                    break;
                case 301:
                    reader.readMessage(message.publicDeals, () => message.publicDeals = dependency_1.PublicDealsV3Api.deserialize(reader));
                    break;
                case 302:
                    reader.readMessage(message.publicIncreaseDepths, () => message.publicIncreaseDepths = dependency_2.PublicIncreaseDepthsV3Api.deserialize(reader));
                    break;
                case 303:
                    reader.readMessage(message.publicLimitDepths, () => message.publicLimitDepths = dependency_3.PublicLimitDepthsV3Api.deserialize(reader));
                    break;
                case 304:
                    reader.readMessage(message.privateOrders, () => message.privateOrders = dependency_4.PrivateOrdersV3Api.deserialize(reader));
                    break;
                case 305:
                    reader.readMessage(message.publicBookTicker, () => message.publicBookTicker = dependency_5.PublicBookTickerV3Api.deserialize(reader));
                    break;
                case 306:
                    reader.readMessage(message.privateDeals, () => message.privateDeals = dependency_6.PrivateDealsV3Api.deserialize(reader));
                    break;
                case 307:
                    reader.readMessage(message.privateAccount, () => message.privateAccount = dependency_7.PrivateAccountV3Api.deserialize(reader));
                    break;
                case 308:
                    reader.readMessage(message.publicSpotKline, () => message.publicSpotKline = dependency_8.PublicSpotKlineV3Api.deserialize(reader));
                    break;
                case 309:
                    reader.readMessage(message.publicMiniTicker, () => message.publicMiniTicker = dependency_9.PublicMiniTickerV3Api.deserialize(reader));
                    break;
                case 310:
                    reader.readMessage(message.publicMiniTickers, () => message.publicMiniTickers = dependency_10.PublicMiniTickersV3Api.deserialize(reader));
                    break;
                case 311:
                    reader.readMessage(message.publicBookTickerBatch, () => message.publicBookTickerBatch = dependency_11.PublicBookTickerBatchV3Api.deserialize(reader));
                    break;
                case 312:
                    reader.readMessage(message.publicIncreaseDepthsBatch, () => message.publicIncreaseDepthsBatch = dependency_12.PublicIncreaseDepthsBatchV3Api.deserialize(reader));
                    break;
                case 313:
                    reader.readMessage(message.publicAggreDepths, () => message.publicAggreDepths = dependency_13.PublicAggreDepthsV3Api.deserialize(reader));
                    break;
                case 314:
                    reader.readMessage(message.publicAggreDeals, () => message.publicAggreDeals = dependency_14.PublicAggreDealsV3Api.deserialize(reader));
                    break;
                case 315:
                    reader.readMessage(message.publicAggreBookTicker, () => message.publicAggreBookTicker = dependency_15.PublicAggreBookTickerV3Api.deserialize(reader));
                    break;
                case 3:
                    message.symbol = reader.readString();
                    break;
                case 4:
                    message.symbolId = reader.readString();
                    break;
                case 5:
                    message.createTime = reader.readInt64();
                    break;
                case 6:
                    message.sendTime = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): PushDataV3ApiWrapper {
        return PushDataV3ApiWrapper.deserialize(bytes);
    }
}
